# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('networkdevice_ptr', models.OneToOneField(auto_created=True,
                                                           on_delete=CASCADE,
                                                           parent_link=True,
                                                           primary_key=True,
                                                           serialize=False,
                                                           to='network.NetworkDevice')),
                ('model', models.CharField(max_length=25, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, default=None, max_length=20,
                                                   null=True, unique=True,
                                                   verbose_name='Serial Number')),
                ('property_id', models.CharField(blank=True, default=None, max_length=50, null=True,
                                                 unique=True, verbose_name='Cal Poly Property ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True,
                                              verbose_name='Location')),
                ('date_purchased', models.DateField(verbose_name='Date Purchased')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('dhcp', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=CASCADE, to='core.Department',
                                                 verbose_name='Department')),
                ('sub_department', models.ForeignKey(on_delete=CASCADE, to='core.SubDepartment',
                                                     verbose_name='Sub Department')),
            ],
            bases=('network.networkdevice',),
        ),
    ]
