# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def create_network_devices_from_printers(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    Printer = apps.get_model('printers', 'Printer')

    for printer in Printer.objects.all():
        network_device = NetworkDevice()
        network_device.display_name = printer.printer_name
        network_device.ip_address = printer.ip_address
        network_device.mac_address = printer.mac_address
        network_device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_auto_20151220_1226'),
    ]

    operations = [
        RunPython(create_network_devices_from_printers)
    ]
