# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def correct_parent_pointer(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    Printer = apps.get_model('printers', 'Printer')

    for printer in Printer.objects.all():
        network_device = NetworkDevice.objects.get(mac_address=printer.old_mac_address)
        printer.networkdevice_ptr = network_device
        printer.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0026_auto_20160224_1044'),
        ('printers', '0007_create_network_devices_from_printers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='ip_address',
            new_name='old_ip_address',
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='mac_address',
            new_name='old_mac_address',
        ),
        migrations.AddField(
            model_name='printer',
            name='networkdevice_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
        migrations.RunPython(
            correct_parent_pointer,
            reverse_code=reverse_code,
        ),
        migrations.RemoveField(
            model_name='printer',
            name='id',
        ),
        migrations.AlterField(
            model_name='printer',
            name='networkdevice_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
    ]
