# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_add_printer_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='old_ip_address',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='old_mac_address',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='printer_name',
        ),
    ]
