# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyduties', '0002_auto_20150901_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPermalink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mailbox', models.CharField(max_length=100)),
                ('current_uid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
