#! /bin/bash

workon resnet_internal_project
git pull | grep 'Already up-to-date.'
UPDATED=$?

if [ $UPDATED = 1 ]; then    
    wipeenv
    pip3 install -qr requirements.txt 
    python3 resnet_internal/manage.py collectstatic --noinput
    touch conf/uwsgi.ini
fi
