# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uh_internal.apps.computers.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearPassLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('service', models.CharField(max_length=50)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('client_mac_address', uh_internal.apps.computers.fields.MACAddressField(max_length=17)),
                ('enforcement_profiles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('accepted', models.BooleanField()),
                ('clearpass_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
