# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_clearpassloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearpassloginattempt',
            name='alerts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
