# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20160330_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearpassloginattempt',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
