# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20160419_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='airwaves_is_up',
            field=models.NullBooleanField(),
        ),
    ]
