# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def correct_parent_pointer(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    NetworkInfrastructureDevice = apps.get_model('portmap', 'NetworkInfrastructureDevice')

    for infrastructure_device in NetworkInfrastructureDevice.objects.all():
        network_device = NetworkDevice.objects.get(ip_address=infrastructure_device.old_ip_address)
        infrastructure_device.networkdevice_ptr = network_device
        infrastructure_device.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0014_create_network_devices_from_infrastructure_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkinfrastructuredevice',
            old_name='ip_address',
            new_name='old_ip_address',
        ),
        migrations.AddField(
            model_name='networkinfrastructuredevice',
            name='networkdevice_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
        migrations.RunPython(
            correct_parent_pointer,
            reverse_code=reverse_code,
        ),
        migrations.RemoveField(
            model_name='networkinfrastructuredevice',
            name='id',
        ),
        migrations.AlterField(
            model_name='networkinfrastructuredevice',
            name='networkdevice_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='networkinfrastructuredevice',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='networkinfrastructuredevice',
            name='dns_name',
        ),
    ]
