# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_move_networkdevice_to_portmap_1'),
        ('portmap', '0019_remove_accesspoint_old_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Room', verbose_name='Room'),
        ),
    ]
