# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0027_auto_20160307_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='airwaves_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
