# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:16
from __future__ import unicode_literals

from django.db import migrations


def add_navbar_link(apps, schema_editor):
    NavbarLink = apps.get_model('core', 'NavbarLink')
    PermissionClass = apps.get_model('core', 'PermissionClass')

    try:
        permission_class = PermissionClass.objects.get(name='network')
        parent = NavbarLink.objects.get(display_name='Network Administration')
    except (PermissionClass.DoesNotExist, NavbarLink.DoesNotExist):
        return

    link = NavbarLink(display_name='Aruba Troubleshooter',
                      icon='images/icons/aruba.png',
                      sequence_index=-1,
                      parent_group=parent,
                      url_name='network:troubleshooter')
    link.save()
    link.permission_classes.add(permission_class)


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_navbar_link, reverse_code=rollback),
    ]
