# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160406_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='permission_classes',
            field=models.ManyToManyField(blank=True, to='core.PermissionClass', verbose_name='Permission Classes'),
        ),
    ]
