# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def correct_parent_pointer(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    Computer = apps.get_model('computers', 'Computer')

    for computer in Computer.objects.all():
        network_device = NetworkDevice.objects.get(mac_address=computer.old_mac_address)
        computer.networkdevice_ptr = network_device
        computer.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0026_auto_20160224_1044'),
        ('computers', '0008_create_network_devices_from_computers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='ip_address',
            new_name='old_ip_address',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='mac_address',
            new_name='old_mac_address',
        ),
        migrations.AddField(
            model_name='computer',
            name='networkdevice_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
        migrations.RunPython(
            correct_parent_pointer,
            reverse_code=reverse_code,
        ),
        migrations.RemoveField(
            model_name='computer',
            name='id',
        ),
        migrations.AlterField(
            model_name='computer',
            name='networkdevice_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
    ]
