# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0010_remove_accesspoint_type'),
        ('core', '0028_move_networkdevice_to_portmap_1'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('dns_name', models.CharField(max_length=75, verbose_name='DNS Name')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP Address')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
