# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0011_move_networkdevice_to_portmap_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkDevice',
            new_name='NetworkInfrastructureDevice',
        ),
    ]
