# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def create_network_devices_from_infrastructure(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    NetworkInfrastructureDevice = apps.get_model('portmap', 'NetworkInfrastructureDevice')

    for infrastructure_device in NetworkInfrastructureDevice.objects.all():
        network_device = NetworkDevice()
        network_device.display_name = infrastructure_device.display_name
        network_device.dns_name = infrastructure_device.dns_name
        network_device.ip_address = infrastructure_device.ip_address
        network_device.save()


def remove_network_devices_from_infrastructure(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    NetworkInfrastructureDevice = apps.get_model('portmap', 'NetworkInfrastructureDevice')

    for infrastructure_device in NetworkInfrastructureDevice.objects.all():
        network_device = NetworkDevice.objects.filter(ip_address=infrastructure_device.ip_address)
        if network_device.exists():
            network_device.remove()


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0013_networkdevice'),
    ]

    operations = [
        RunPython(create_network_devices_from_infrastructure, reverse_code=remove_network_devices_from_infrastructure)
    ]
