# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def correct_parent_pointer(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    AccessPoint = apps.get_model('portmap', 'AccessPoint')

    for access_point in AccessPoint.objects.all():
        network_device = NetworkDevice.objects.get(mac_address=access_point.old_mac_address)
        access_point.networkdevice_ptr = network_device
        access_point.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0017_create_network_devices_from_accesspoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspoint',
            old_name='mac_address',
            new_name='old_mac_address',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='networkdevice_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
        migrations.RunPython(
            correct_parent_pointer,
            reverse_code=reverse_code,
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='name',
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='networkdevice_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portmap.NetworkDevice'),
            preserve_default=False,
        ),
    ]
