# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0018_add_accesspoint_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='old_mac_address',
        ),
    ]
