# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:41
from __future__ import unicode_literals

from django.db import migrations


def update_fk(apps, schema_editor):
    AccessPoint = apps.get_model('portmap', 'AccessPoint')
    Port = apps.get_model('portmap', 'Port')
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')

    input('Packet capture now.')

    for access_point in AccessPoint.objects.all():
        port = Port.objects.get(old_id=access_point.old_port)
        network_device = NetworkDevice.objects.get(id=access_point.networkdevice_ptr.id)
        network_device.upstream_device = port.networkdevice_ptr
        network_device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0022_add_port_inheritance'),
    ]

    operations = [
        migrations.RunPython(
            update_fk,
        ),
    ]
