# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0023_accesspoint_update_port_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='old_jack',
        ),
        migrations.RemoveField(
            model_name='port',
            name='old_room',
        ),
        migrations.RemoveField(
            model_name='port',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='old_port',
        ),
    ]
