# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 14:02
from __future__ import unicode_literals

from django.db import migrations


def add_room_to_accesspoints(apps, schema_editor):
    AccessPoint = apps.get_model('portmap', 'AccessPoint')

    for access_point in AccessPoint.objects.all():
        network_device = access_point.networkdevice_ptr
        network_device.room = network_device.upstream_device.room
        network_device.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0024_port_remove_legacy_fields'),
    ]

    operations = [
        migrations.RunPython(add_room_to_accesspoints, reverse_code=reverse_code)
    ]
