# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestor',
            field=models.CharField(max_length=50),
        ),
    ]
