# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 18:26
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def add_printer_types_toner_parts(apps, schema_editor):
    PrinterType = apps.get_model('printerrequests', 'PrinterType')
    Toner = apps.get_model('printerrequests', 'Toner')
    Part = apps.get_model('printerrequests', 'Part')

    # Populate printer types
    dell_5100cn = PrinterType.objects.create(
        make="Dell",
        model="5100cn",
        servicable=True
    )

    dell_5130cn = PrinterType.objects.create(
        make="Dell",
        model="5130cdn",
        servicable=True
    )

    dell_B1260dn = PrinterType.objects.create(
        make="Dell",
        model="B1260dn",
        servicable=True
    )

    # Populate parts
    Part.objects.create(
        type="Toner Waste Container",
        printer=dell_5130cn,
        quantity=10,
        ordered=0
    )
    Part.objects.create(
        type="Fuser",
        printer=dell_5130cn,
        quantity=8,
        ordered=0
    )
    Part.objects.create(
        type="Transfer Roller",
        printer=dell_5130cn,
        quantity=1,
        ordered=0
    )
    Part.objects.create(
        type="Black Imaging Drum",
        printer=dell_5130cn,
        quantity=2,
        ordered=0
    )
    Part.objects.create(
        type="Cyan Imaging Drum",
        printer=dell_5130cn,
        quantity=7,
        ordered=0
    )
    Part.objects.create(
        type="Magenta Imaging Drum",
        printer=dell_5130cn,
        quantity=7,
        ordered=0
    )
    Part.objects.create(
        type="Yellow Imaging Drum",
        printer=dell_5130cn,
        quantity=7,
        ordered=0
    )

    Part.objects.create(
        type="Fuser",
        printer=dell_5100cn,
        quantity=8,
        ordered=0
    )
    Part.objects.create(
        type="Transfer Roller",
        printer=dell_5100cn,
        quantity=0,
        ordered=0
    )
    Part.objects.create(
        type="Imaging Drum",
        printer=dell_5100cn,
        quantity=11,
        ordered=0
    )

    # Populate toner
    Toner.objects.create(
        color="Black",
        printer=dell_5130cn,
        quantity=12,
        ordered=0
    )
    Toner.objects.create(
        color="Cyan",
        printer=dell_5130cn,
        quantity=10,
        ordered=0
    )
    Toner.objects.create(
        color="Magenta",
        printer=dell_5130cn,
        quantity=12,
        ordered=0
    )
    Toner.objects.create(
        color="Yellow",
        printer=dell_5130cn,
        quantity=12,
        ordered=0
    )

    Toner.objects.create(
        color="Black",
        printer=dell_5100cn,
        quantity=6,
        ordered=0
    )
    Toner.objects.create(
        color="Cyan",
        printer=dell_5100cn,
        quantity=7,
        ordered=0
    )
    Toner.objects.create(
        color="Magenta",
        printer=dell_5100cn,
        quantity=7,
        ordered=0
    )
    Toner.objects.create(
        color="Yellow",
        printer=dell_5100cn,
        quantity=8,
        ordered=0
    )

    Toner.objects.create(
        color="Black",
        printer=dell_B1260dn,
        quantity=8,
        ordered=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('printerrequests', '0002_auto_20160312_1548'),
    ]

    operations = [
        RunPython(add_printer_types_toner_parts),
    ]
