# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerrequests', '0002_auto_20160404_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='parts',
            field=models.ManyToManyField(blank=True, to='printerrequests.Part'),
        ),
        migrations.AlterField(
            model_name='request',
            name='toner',
            field=models.ManyToManyField(blank=True, to='printerrequests.Toner'),
        ),
    ]
