# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resnet_internal.apps.computers.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0012_rename_infrastructure_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('dns_name', models.CharField(null=True, max_length=75, verbose_name='DNS Name')),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4', verbose_name='IP Address')),
                ('mac_address', resnet_internal.apps.computers.fields.MACAddressField(null=True, max_length=17, verbose_name='MAC Address')),
                ('upstream_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_networkdevice', to='portmap.NetworkDevice')),
            ],
        ),
    ]
