# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0015_add_infrastructure_device_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinfrastructuredevice',
            name='old_ip_address',
        ),
    ]
