# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def create_network_devices_from_accesspoints(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    AccessPoint = apps.get_model('portmap', 'AccessPoint')

    for access_point in AccessPoint.objects.all():
        network_device = NetworkDevice()
        network_device.display_name = access_point.name
        network_device.dns_name = access_point.name
        network_device.ip_address = access_point.ip_address
        network_device.mac_address = access_point.mac_address
        network_device.save()


def remove_network_devices_from_accesspoints(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    AccessPoint = apps.get_model('portmap', 'AccessPoint')

    for access_point in AccessPoint.objects.all():
        network_device = NetworkDevice.objects.filter(mac_address=access_point.mac_address)
        if network_device.exists():
            network_device.remove()


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0016_remove_networkinfrastructuredevice_old_ip_address'),
    ]

    operations = [
        RunPython(create_network_devices_from_accesspoints, reverse_code=remove_network_devices_from_accesspoints)
    ]
