# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def create_network_devices_from_ports(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    Port = apps.get_model('portmap', 'Port')

    for port in Port.objects.all():
        network_device = NetworkDevice()

        network_device.display_name = port.jack
        network_device.room = port.room
        network_device.upstream_device = NetworkDevice.objects.get(ip_address=port.switch_ip)

        network_device.save()


def remove_network_devices_from_ports(apps, schema_editor):
    NetworkDevice = apps.get_model('portmap', 'NetworkDevice')
    Port = apps.get_model('portmap', 'Port')

    for port in Port.objects.all():
        network_device = NetworkDevice.objects.filter(display_name=port.jack, room=port.room)
        if network_device.exists():
            network_device.remove()


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0020_networkdevice_room'),
    ]

    operations = [
        RunPython(create_network_devices_from_ports, reverse_code=remove_network_devices_from_ports)
    ]
