# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portmap', '0025_add_room_to_accesspoints_from_upstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='upstream_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_devices', to='portmap.NetworkDevice'),
        ),
    ]
