# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_add_computer_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='computer_name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='old_ip_address',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='old_mac_address',
        ),
    ]
