# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20151220_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resnetinternaluser',
            options={'verbose_name': 'University Housing Internal User'},
        ),

    ]
