# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models
# from django.db.migrations.operations.special import RunPython
import django.db.models.deletion


def populate_csd_mapping(apps, schema_editor):
    ADGroup = apps.get_model('core', 'ADGroup')
    CSDMapping = apps.get_model('core', 'CSDMapping')

    ad_group_01 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Fremont,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Fremont"
    )
    csd_mapping_01 = CSDMapping.objects.create(
        name="Amanda Baker",
        email="abaker05@calpoly.edu",
        domain="Fremont",
        ad_group=ad_group_01,
    )
    csd_mapping_01.buildings.add(16)

    ad_group_02 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Muir,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Muir"
    )
    csd_mapping_02 = CSDMapping.objects.create(
        name="Sergio Perez",
        email="sperez32@calpoly.edu",
        domain="Muir",
        ad_group=ad_group_02,
    )
    csd_mapping_02.buildings.add(17)

    ad_group_03 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Santa Lucia,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Santa Lucia"
    )
    csd_mapping_03 = CSDMapping.objects.create(
        name="Bruce Brown",
        email="bbrown25@calpoly.edu",
        domain="Santa Lucia",
        ad_group=ad_group_03,
    )
    csd_mapping_03.buildings.add(18, 22, 23, 24, 25, 26)  # Santa Lucia, North Mountain

    ad_group_04 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Sequoia,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Sequoia"
    )
    csd_mapping_04 = CSDMapping.objects.create(
        name="uhtest",
        email="uhtest@calpoly.edu",
        domain="Sequoia",
        ad_group=ad_group_04,
    )
    csd_mapping_04.buildings.add(19)

    ad_group_05 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Sierra Madre,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Sierra Madre"
    )
    csd_mapping_05 = CSDMapping.objects.create(
        name="Stephen Ross",
        email="sdross@calpoly.edu",
        domain="Sierra Madre",
        ad_group=ad_group_05,
    )
    csd_mapping_05.buildings.add(43, 44, 45, 46, 47, 48)  # Towers 0 - 5

    ad_group_06 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Tenaya,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Tenaya"
    )
    csd_mapping_06 = CSDMapping.objects.create(
        name="Jill Rounds",
        email="jrounds@calpoly.edu",
        domain="Tenaya",
        ad_group=ad_group_06,
    )
    csd_mapping_06.buildings.add(20)

    ad_group_07 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Trinity,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Trinity"
    )
    csd_mapping_07 = CSDMapping.objects.create(
        name="Blaze Campbell",
        email="bcampb11@calpoly.edu",
        domain="Trinity",
        ad_group=ad_group_07,
    )
    csd_mapping_07.buildings.add(21)

    ad_group_08 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Yosemite,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Yosemite"
    )
    csd_mapping_08 = CSDMapping.objects.create(
        name="Matthew Soto",
        email="msoto12@calpoly.edu",
        domain="Yosemite",
        ad_group=ad_group_08,
    )
    csd_mapping_08.buildings.add(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)  # Towers 0 - 9

    cerro_vista_ad_group = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Cerro Vista,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Cerro Vista"
    )
    cerro_vista_buildings = [27, 28, 29, 30, 31, 32]  # Bishop, Cabrillo, Hollister, Islay, Morror, Romauldo

    csd_mapping_09 = CSDMapping.objects.create(
        name="Mindy Sackett",
        email="mjsacket@calpoly.edu",
        domain="Cerro Vista 1",
        ad_group=cerro_vista_ad_group,
    )
    csd_mapping_09.buildings.add(*cerro_vista_buildings)

    csd_mapping_10 = CSDMapping.objects.create(
        name="Kem French",
        email="kfrenc01@calpoly.edu",
        domain="Cerro Vista 2",
        ad_group=cerro_vista_ad_group,
    )
    csd_mapping_10.buildings.add(*cerro_vista_buildings)

    ad_group_11 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Aliso,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Poly Canyon Village 1"
    )
    csd_mapping_11 = CSDMapping.objects.create(
        name="Jamica Johnson",
        email="jjohn160@calpoly.edu",
        domain="Poly Canyon Village 1",
        ad_group=ad_group_11,
    )
    csd_mapping_11.buildings.add(34, 35, 42)  # Aliso, Buena Vista, Inyo

    ad_group_12 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Estrella,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Poly Canyon Village 2"
    )
    csd_mapping_12 = CSDMapping.objects.create(
        name="Timothy Nurge",
        email="tnurge@calpoly.edu",
        domain="Poly Canyon Village 2",
        ad_group=ad_group_12,
    )
    csd_mapping_12.buildings.add(36, 37, 38)  # Corralitos, Dover, Estrella

    ad_group_13 = ADGroup.objects.create(
        distinguished_name="CN=UH-FD-Huasna,OU=Front Desk,OU=Residential Life,OU=UH,OU=Manual,OU=Groups,DC=ad,DC=calpoly,DC=edu",
        display_name="Poly Canyon Village 3"
    )
    csd_mapping_13 = CSDMapping.objects.create(
        name="Amy Skoll",
        email="askoll@calpoly.edu",
        domain="Poly Canyon Village 3",
        ad_group=ad_group_13,
    )
    csd_mapping_13.buildings.add(39, 40, 41)  # Foxen, Gypsum, Huasna


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_switch_to_managed_staffmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('domain', models.CharField(max_length=35, unique=True, verbose_name='Domain')),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ADGroup', verbose_name='Domain AD Group')),
                ('buildings', models.ManyToManyField(related_name='csdmappings', to='core.Building', verbose_name='Domain Buildings')),
            ],
            options={
                'verbose_name': 'CSD Domain Mapping',
            },
        ),
        #  RunPython(populate_csd_mapping),
        migrations.AlterField(
            model_name='resnetinternaluser',
            name='ad_groups',
            field=models.ManyToManyField(to='core.ADGroup', verbose_name='AD Groups'),
        ),
        migrations.AlterField(
            model_name='staffmapping',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Email Address'),
        ),
    ]
