# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:49
from __future__ import unicode_literals

from django.db import migrations
# from django.db.migrations.operations.special import RunPython


def update_navbar(apps, schema_editor):
    NavbarLink = apps.get_model('core', 'NavbarLink')

    reslife_resources = NavbarLink.objects.get(display_name="Reslife Resources")

    resident_lookup = NavbarLink.objects.create(
        display_name="Resident Lookup",
        sequence_index=1,
        url_name="resident_lookup",
        icon="images/icons/residents.png",
        parent_group=reslife_resources
    )
    resident_lookup.groups.add(20, 21, 22, 23, 24, 5, 6, 7)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_added_roster_navbar_links'),
    ]

    operations = [
        #  RunPython(update_navbar),
    ]
