# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:33
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def change_navbar_urls(apps, schema_editor):
    NavbarLink = apps.get_model('core', 'NavbarLink')

    computers = NavbarLink.objects.filter(display_name="Computers")
    if computers.exists():
        computers.url_name = "computers"
        computers.save()

    printers = NavbarLink.objects.filter(display_name="Printers")
    if printers.exists():
        printers.url_name = "printers"
        printers.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_added_residents_navbar_links'),
    ]

    operations = [
        RunPython(change_navbar_urls),
    ]
