# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 15:34
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def add_navbar_item(apps, schema_editor):
    ADGroup = apps.get_model('core', 'ADGroup')
    NavbarLink = apps.get_model('core', 'NavbarLink')

    reslife_resources = NavbarLink.objects.filter(display_name="Reslife Resources")
    if reslife_resources.exists():
        reslife_resources = reslife_resources.first()

        csd_domain_assignments = NavbarLink.objects.create(
            display_name="CSD Domain Assignments",
            sequence_index=2,
            url_name="csd_assign_domain",
            icon="images/icons/person.png",
            parent_group=reslife_resources
        )

        ad_group_names = ["Residential Life Manager", "ResNet Staff", "ResNet Developer", "ResNet Technician"]

        for name in ad_group_names:
            try:
                ad_group = ADGroup.objects.get(display_name=name)
            except ADGroup.DoesNotExist:
                continue
            else:
                csd_domain_assignments.groups.add(ad_group)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_DATA_renamed_urls'),
    ]

    operations = [
        RunPython(add_navbar_item),
    ]
