# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_DATA_add_csd_domain_assign_to_navbar'),
    ]

    database_operations = [
        migrations.AlterModelTable('NetworkDevice', 'portmap_networkdevice')
    ]

    state_operations = [
        migrations.DeleteModel('NetworkDevice')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
