# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20160226_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_csd',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_fd_staff',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_net_admin',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_new_tech',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_ra',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_ral',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_ral_manager',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_rn_staff',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_tag',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_tag_readonly',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_technician',
        ),
        migrations.RemoveField(
            model_name='resnetinternaluser',
            name='is_telecom',
        ),
    ]
