# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20160226_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionclass',
            options={'verbose_name_plural': 'permission classes'},
        ),
    ]
