# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_DATA_add_printerrequest_navbar_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteannouncements',
            name='permission_classes',
            field=models.ManyToManyField(blank=True, related_name='site_announcements', to='core.PermissionClass'),
        ),
    ]
