# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDuties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Duty Name')),
                ('last_checked', models.DateTimeField(verbose_name='Last DateTime Checked')),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Last User to Check')),
            ],
            options={
                'verbose_name': 'Daily Duty',
                'verbose_name_plural': 'Daily Duties',
            },
        ),
        migrations.CreateModel(
            name='EmailPermalink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mailbox', models.CharField(max_length=100)),
                ('current_uid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
