# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyduties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailViewingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(max_length=100)),
                ('uid', models.IntegerField()),
                ('replying', models.BooleanField()),
                ('expiry_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
