# Generated by Django 2.0.4 on 2018-04-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyduties', '0002_emailviewingrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailPermalink',
        ),
        migrations.RemoveField(
            model_name='emailviewingrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailViewingRecord',
        ),
    ]
